Fixed "Unconsumed Column" bug in dCacheDataManagement.
The module used to throw an exception during acquisition when trying to insert
module data:
 CompileError: Unconsumed column names: duration

The error was caused by blindly filling elements from the XML tree into the
data structure passed to the database. This fix will make the module run
without error in normal operation.

git-svn-id: https://ekptrac.physik.uni-karlsruhe.de/svn/HappyFaceModules/trunk@128 59e662cd-a22a-4296-a36a-137269dfb10d